"""AI Report Generator module.

Compiles complete analytics summaries, data quality lists, correlations, and
smart recommendations into formatted Markdown files and saves to state memory.
"""

import os
import json
from datetime import datetime

import pandas as pd
import numpy as np

from src.utils.paths import ensure_dirs

from src.core.ai_analytics import (
    summarize_df,
    detect_anomalies,
)

from src.core.smart_recommendations import (
    recommend_from_storage,
)


def log(msg):
    """Outputs a formatted console log message.

    Args:
        msg: Message string.
    """
    print(f"[REPORT_GENERATOR] {msg}")


def storage_to_df(storage: dict) -> pd.DataFrame:
    """Converts the session storage representation into a pandas DataFrame.

    Args:
        storage: Web app session state dictionary.

    Returns:
        Pandas DataFrame reconstructed from JSON storage representation.
    """

    rows = storage.get("df_json", [])

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows)

    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col])
        except Exception:
            pass

    return df


def numeric_columns(df):
    """Extracts column headers containing numeric-convertible data.

    Args:
        df: Pandas DataFrame.

    Returns:
        List of numeric column header name strings.
    """

    if df.empty:
        return []

    return list(
        df.select_dtypes(
            include=[np.number]
        ).columns
    )


def missing_values_report(df):
    """Lists columns containing missing values along with their count.

    Args:
        df: Pandas DataFrame.

    Returns:
        List of strings detailing missing value counts.
    """

    if df.empty:
        return ["No dataset loaded."]

    miss = df.isna().sum()
    miss = miss[miss > 0]

    if len(miss) == 0:
        return ["No missing values detected."]

    lines = []

    for col, val in miss.items():
        lines.append(
            f"{col}: {int(val)} missing"
        )

    return lines


def correlations_report(df):
    """Identifies top absolute correlations between numeric columns.

    Args:
        df: Pandas DataFrame.

    Returns:
        List of correlation strength descriptions.
    """

    nums = numeric_columns(df)

    if len(nums) < 2:
        return ["Not enough numeric columns."]

    numeric_df = (
        df[nums]
        .apply(pd.to_numeric, errors="coerce")
    )
    
    corr = (
        numeric_df
        .corr(numeric_only=True)
        .abs()
        .unstack()
        .sort_values(ascending=False)
    )

    used = set()
    lines = []

    for (a, b), val in corr.items():

        if a == b:
            continue

        key = tuple(sorted([a, b]))

        if key in used:
            continue

        used.add(key)

        lines.append(
            f"{a} vs {b}: {round(float(val),3)}"
        )

        if len(lines) >= 5:
            break

    if len(lines) == 0:
        lines.append("No strong correlations.")

    return lines


def build_markdown_report(storage: dict):
    """Assembles all data quality, summaries, and recommendations into markdown.

    Args:
        storage: Web app session state dictionary.

    Returns:
        Formatted markdown report string.
    """

    log("Building markdown report")

    df = storage_to_df(storage)

    now = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    if df.empty:

        text = f"""
# Raw2Ready AI Report

Generated: {now}

## Status
No dataset loaded.
"""
        return text

    rows = len(df)
    cols = len(df.columns)

    summary = summarize_df(df)
    anomalies = detect_anomalies(df)
    missing = missing_values_report(df)
    corr = correlations_report(df)
    recs = recommend_from_storage(storage)

    text = f"""
# Raw2Ready Enterprise AI Report

Generated: {now}

---

## Executive Summary

Dataset contains **{rows} rows** and **{cols} columns**.

---

## Dataset Summary
"""

    for line in summary:
        text += f"- {line}\n"

    text += "\n---\n## Data Quality / Anomalies\n"

    for line in anomalies:
        text += f"- {line}\n"

    text += "\n---\n## Missing Values\n"

    for line in missing:
        text += f"- {line}\n"

    text += "\n---\n## Correlation Insights\n"

    for line in corr:
        text += f"- {line}\n"

    text += "\n---\n## AI Recommendations\n"

    for line in recs:
        text += f"- {line}\n"

    text += """
---

## Final Notes

This report was automatically generated by Raw2Ready AI Reporting Engine.

Suggested next actions:
- Clean missing values
- Investigate anomalies
- Build forecasts
- Generate charts
- Deploy monitoring dashboard
"""

    log("Markdown report ready")

    return text


def save_report_to_memory(
    storage,
    markdown_text,
):
    """Saves generated markdown text and timestamp metadata to runtime storage.

    Args:
        storage: Web app session state dictionary.
        markdown_text: Raw markdown text string.
    """

    storage["generated_report"] = markdown_text
    storage["generated_report_timestamp"] = datetime.now().isoformat()
    log("Report stored in Runtime Memory.")


def generate_report_file(
    storage: dict,
    output_folder=None,
):
    """Generates markdown report content, writes it to a file, and saves to state memory.

    Args:
        storage: Web app session state dictionary.
        output_folder: Output folder path. Defaults to DIRS["reports"].

    Returns:
        Report status dictionary containing title, message lines, and saved file path.
    """

    if output_folder is None:
        output_folder = str(ensure_dirs()["reports"])

    os.makedirs(
        output_folder,
        exist_ok=True,
    )

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    filename = (
        f"raw2ready_report_{timestamp}.md"
    )

    path = os.path.join(
        output_folder,
        filename,
    )

    content = build_markdown_report(
        storage
    )

    with open(
        path,
        "w",
        encoding="utf-8"
    ) as f:
        f.write(content)

    # --------------------------------------
    # SAVE TO POSTGRESQL
    # --------------------------------------
    save_report_to_memory(
        storage=storage,
        markdown_text=content,
    )

    log(f"Saved report: {path}")

    return {
        "title": "AI Report Generated",
        "lines": [
            "File saved successfully.",
            f"Location: {path}",
            "Saved to Runtime Memory.",
            "Open the .md file to view the report."
        ],
        "path": path,
    }


def ask_report(storage: dict):
    """Trigger function for the report generation sequence.

    Args:
        storage: Web app session state dictionary.

    Returns:
        Report status dictionary.
    """

    return generate_report_file(
        storage
    )